In [41]:
class_algebra_table = {
    "C1": {
        "C1": {"C1": 1},
        "C2": {"C2": 1},
        "C3": {"C3": 1},
        "C4": {"C4": 1},
        "C5": {"C5": 1}
    },
    "C2": {
        "C1": {"C2": 1},
        "C2": {"C1": 20, "C2": 7, "C3": 8, "C4": 5, "C5": 5},
        "C3": {"C2": 6, "C3": 4, "C4": 5, "C5": 5},
        "C4": {"C2": 3, "C3": 4, "C4": 5, "C5": 5},
        "C5": {"C2": 3, "C3": 4, "C4": 5, "C5": 5}
    },
    "C3": {
        "C1": {"C3": 1},
        "C2": {"C2": 6, "C3": 4, "C4": 5, "C5": 5},
        "C3": {"C1": 15, "C2": 3, "C3": 2, "C4": 5, "C5": 5},
        "C4": {"C2": 3, "C3": 4, "C5": 5},
        "C5": {"C2": 3, "C3": 4, "C4": 5}
    },
    "C4": {
        "C1": {"C4": 1},
        "C2": {"C2": 3, "C3": 4, "C4": 5, "C5": 5},
        "C3": {"C2": 3, "C3": 4, "C5": 5},
        "C4": {"C1": 12, "C2": 3, "C4": 5, "C5": 1},
        "C5": {"C2": 3, "C3": 4, "C4": 1, "C5": 1}
    },
    "C5": {
        "C1": {"C5": 1},
        "C2": {"C2": 3, "C3": 4, "C4": 5, "C5": 5},
        "C3": {"C2": 3, "C3": 4, "C4": 5},
        "C4": {"C2": 3, "C3": 4, "C4": 1, "C5": 1},
        "C5": {"C1": 12, "C2": 3, "C4": 1, "C5": 5}
    }
}

# Function to display the class algebra table
def display_class_algebra_table(table):
    for key, value in table.items():
        print(f"{key}:")
        for subkey, subvalue in value.items():
            terms = " + ".join([f"{count}*{cls}" for cls, count in subvalue.items()])
            print(f"  {key} * {subkey} = {terms}")

# Display the class algebra table
display_class_algebra_table(class_algebra_table)

C1:
  C1 * C1 = 1*C1
  C1 * C2 = 1*C2
  C1 * C3 = 1*C3
  C1 * C4 = 1*C4
  C1 * C5 = 1*C5
C2:
  C2 * C1 = 1*C2
  C2 * C2 = 20*C1 + 7*C2 + 8*C3 + 5*C4 + 5*C5
  C2 * C3 = 6*C2 + 4*C3 + 5*C4 + 5*C5
  C2 * C4 = 3*C2 + 4*C3 + 5*C4 + 5*C5
  C2 * C5 = 3*C2 + 4*C3 + 5*C4 + 5*C5
C3:
  C3 * C1 = 1*C3
  C3 * C2 = 6*C2 + 4*C3 + 5*C4 + 5*C5
  C3 * C3 = 15*C1 + 3*C2 + 2*C3 + 5*C4 + 5*C5
  C3 * C4 = 3*C2 + 4*C3 + 5*C5
  C3 * C5 = 3*C2 + 4*C3 + 5*C4
C4:
  C4 * C1 = 1*C4
  C4 * C2 = 3*C2 + 4*C3 + 5*C4 + 5*C5
  C4 * C3 = 3*C2 + 4*C3 + 5*C5
  C4 * C4 = 12*C1 + 3*C2 + 5*C4 + 1*C5
  C4 * C5 = 3*C2 + 4*C3 + 1*C4 + 1*C5
C5:
  C5 * C1 = 1*C5
  C5 * C2 = 3*C2 + 4*C3 + 5*C4 + 5*C5
  C5 * C3 = 3*C2 + 4*C3 + 5*C4
  C5 * C4 = 3*C2 + 4*C3 + 1*C4 + 1*C5
  C5 * C5 = 12*C1 + 3*C2 + 1*C4 + 5*C5


In [39]:
import numpy as np
from scipy.linalg import eig

# Define the conjugacy classes and their sizes for A5
conjugacy_classes = {
    "C1": 1,
    "C2": 20,
    "C3": 15,
    "C4": 12,
    "C5": 12
}


def construct_regular_representation(class_algebra, conjugacy_classes):
    size = len(conjugacy_classes)  # The size of the matrices is the number of conjugacy classes
    matrices = {}

    # Create a mapping from conjugacy class names to indices
    class_indices = {cls: idx for idx, cls in enumerate(conjugacy_classes)}

    # Fill in the matrix based on the class algebra table
    for class1, operations in class_algebra.items():
        matrix = np.zeros((size, size))
        for class2, results in operations.items():
            idx1 = class_indices[class2]
            for result_class, count in results.items():
                idx2 = class_indices[result_class]
                matrix[idx1, idx2] += count
        matrices[class1] = matrix

    return matrices

# Construct the regular representation matrices
regular_rep_matrices = construct_regular_representation(class_algebra_table, conjugacy_classes)

# Function to compute eigenvalues and eigenvectors
def compute_eigenvalues(matrix):
    eigenvalues, eigenvectors = eig(matrix)
    return eigenvalues, eigenvectors

# Compute eigenvalues and eigenvectors for each matrix
eigenvalues_and_vectors = {class_name: compute_eigenvalues(matrix) for class_name, matrix in regular_rep_matrices.items()}

# Display the eigenvalues
for class_name, (eigenvalues, eigenvectors) in eigenvalues_and_vectors.items():
    dim = np.sqrt(sum((eigenvalues**2 / np.array([1,2,3,4,5]))))
    print(f"Eigenvalues for {class_name}: {eigenvalues}, {dim}")

# Match eigenvalues to form irreducible characters

phi = 0.5 * (1 + np.sqrt(5))

irreducible_characters = {
    "C1": [1, 3,3,4,5],
    "C2": [1, 0, 0, 1, -1],
    "C3": [1, -1, -1, 0, 1],
    "C4": [1, phi, -1/phi, -1, 0],
    "C5": [1, -1/phi, phi, -1, 0]
}

# Construct a dictionary to store the irreducible representations
irreps = {}
for i, (class_name, character_values) in enumerate(irreducible_characters.items()):
    irreps[f"irrep_{i+1}"] = {
        "class_name": class_name,
        "dimension": character_values[0],  # dimension is the character of the identity element
        "characters": character_values
    }

# Display the irreducible representations
for irrep, data in irreps.items():
    print(f"{irrep}:")
    print(f"  Class: {data['class_name']}")
    print(f"  Dimension: {data['dimension']}")
    print(f"  Characters: {data['characters']}")


Eigenvalues for C1: [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j], (1.5110702608857516+0j)
Eigenvalues for C2: [ 2.00000000e+01+0.j  5.00000000e+00+0.j -4.00000000e+00+0.j
 -1.78108828e-17+0.j -6.38924833e-16+0.j], (20.44097192731632+0j)
Eigenvalues for C3: [ 1.50000000e+01+0.j -5.00000000e+00+0.j  3.00000000e+00+0.j
 -2.55863481e-16+0.j -5.00000000e+00+0.j], (15.668439615992392+0j)
Eigenvalues for C4: [ 1.20000000e+01+0.j  6.47213595e+00+0.j -2.21487392e-16+0.j
 -3.00000000e+00+0.j -2.47213595e+00+0.j], (12.97754072025973+0j)
Eigenvalues for C5: [ 1.20000000e+01+0.j  6.47213595e+00+0.j  4.32394132e-16+0.j
 -3.00000000e+00+0.j -2.47213595e+00+0.j], (12.977540720259737+0j)
<class 'numpy.ndarray'>
Character Table of the Icosahedral Group:
[[ 1.          3.          3.          4.          5.        ]
 [ 1.          0.          0.          1.         -1.        ]
 [ 1.         -1.         -1.          0.          1.        ]
 [ 1.          1.61803399 -0.61803399 -1.          0.        ]
 [ 1.     

In [35]:
print(regular_rep_matrices['C2'])

[[ 0.  1.  0.  0.  0.]
 [20.  7.  8.  5.  5.]
 [ 0.  6.  4.  5.  5.]
 [ 0.  3.  4.  5.  5.]
 [ 0.  3.  4.  5.  5.]]


In [68]:
print(eigenvalues_and_vectors.items())

dict_items([('C1', (array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]), array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]]))), ('C2', (array([ 2.00000000e+01+0.j,  5.00000000e+00+0.j, -4.00000000e+00+0.j,
       -1.78108828e-17+0.j, -6.38924833e-16+0.j]), array([[ 3.30770601e-02, -1.50755672e-01,  1.96116135e-01,
        -2.13237464e-02, -1.67406312e-01],
       [ 6.61541202e-01, -7.53778361e-01, -7.84464541e-01,
        -8.65261612e-18,  2.88658388e-17],
       [ 4.96155901e-01, -1.42054092e-16,  5.88348405e-01,
         1.06618732e-01,  8.37031558e-01],
       [ 3.96924721e-01,  4.52267017e-01,  3.02894160e-17,
        -7.44267093e-01, -4.88361170e-01],
       [ 3.96924721e-01,  4.52267017e-01,  3.02894160e-17,
         6.58972107e-01, -1.81264076e-01]]))), ('C3', (array([ 1.50000000e+01+0.j, -5.00000000e+00+0.j,  3.00000000e+00+0.j,
       -2.55863481e-16+0.j, -5.00000000e+00+0.j]), array([[-3

In [57]:
eigenvalues_and_vectors = {class_name: compute_eigenvalues(matrix) for class_name, matrix in regular_rep_matrices.items()}

print(eigenvalues_and_vectors["C2"][0])

matched_irreps = {}

for class_name, (eigenvalues, eigenvectors) in eigenvalues_and_vectors.items():
    eigenvalues = np.round(eigenvalues, decimals=10)  # Round for numerical stability
    unique_eigenvalues, counts = np.unique(eigenvalues, return_counts=True)
    
    # Initialize a dictionary to store the matched irreps for the class
    matched_irreps[class_name] = {}
    
    for dimension in irreducible_characters["C1"]:
        # Find eigenvalues that match the dimension
        matching_eigenvalues = unique_eigenvalues[counts == dimension]
        
        # Store the matched irreps
        matched_irreps[class_name][dimension] = matching_eigenvalues
matched_irreps


[ 2.00000000e+01+0.j  5.00000000e+00+0.j -4.00000000e+00+0.j
 -1.78108828e-17+0.j -6.38924833e-16+0.j]


{'C1': {1: array([], dtype=complex128),
  3: array([], dtype=complex128),
  4: array([], dtype=complex128),
  5: array([1.+0.j])},
 'C2': {1: array([-4.+0.j,  5.+0.j, 20.+0.j]),
  3: array([], dtype=complex128),
  4: array([], dtype=complex128),
  5: array([], dtype=complex128)},
 'C3': {1: array([-0.+0.j,  3.+0.j, 15.+0.j]),
  3: array([], dtype=complex128),
  4: array([], dtype=complex128),
  5: array([], dtype=complex128)},
 'C4': {1: array([-3.        +0.j, -2.47213596+0.j, -0.        +0.j,  6.47213595+0.j,
         12.        +0.j]),
  3: array([], dtype=complex128),
  4: array([], dtype=complex128),
  5: array([], dtype=complex128)},
 'C5': {1: array([-3.        +0.j, -2.47213596+0.j,  0.        +0.j,  6.47213595+0.j,
         12.        +0.j]),
  3: array([], dtype=complex128),
  4: array([], dtype=complex128),
  5: array([], dtype=complex128)}}

In [77]:
irreducible_dimensions = [1,3,3,4,5]
# Total order of A5
order_A5 = 60

# Function to form projectors and extract irreps
def form_projectors_and_extract_irreps(regular_rep_matrices, character_table, irrep_dimensions):
    irreps = {}

    for irrep, dim in irrep_dimensions.items():
        projector = np.zeros((5, 5), dtype=complex)
        
        for class_name, characters in character_table.items():
            chi = characters[list(irrep_dimensions.keys()).index(irrep)]  # χi for the i-th irrep
            projector += chi * regular_rep_matrices[class_name]
        
        projector = (dim / order_A5) * projector
        
        # Diagonalize the projector to find eigenvalues and eigenvectors
        eigenvalues, eigenvectors = compute_eigenvalues(projector)
        
        # Extract non-zero eigenvalues and corresponding eigenvectors
        non_zero_indices = np.where(np.abs(eigenvalues) > 1e-10)[0]
        irreps[irrep] = eigenvectors[:, non_zero_indices]
    
    return irreps

# Compute the irreps of A5
irreps = form_projectors_and_extract_irreps(regular_rep_matrices, irreducible_characters, irrep_dimensions)

# Output the irreps
print("Irreducible representations of A5:")
for irrep, matrix in irreps.items():
    print(f"{irrep}:")
    print(matrix)


SyntaxError: invalid syntax (3765823966.py, line 22)

In [82]:
import sympy as sp
block_sizes = [1,3,3,3,3,3,3,4,4,4,4,5,5,5,5,5]

# Create a list to store the blocks
blocks = []

# For each block size
for size in block_sizes:
    # Create a matrix of the given size with symbolic elements
    block = sp.Matrix(size, size, lambda i, j: sp.var(f'a_{size}_{i}{j}'))
    # Add the block to the list of blocks
    blocks.append(block)

# Create a block diagonal matrix from the blocks
matrix = sp.BlockDiagMatrix(*blocks)

# Print the matrix
display(matrix)


Matrix([
[Matrix([[a_1_00]]),                                                                                       0,                                                                                       0,                                                                                       0,                                                                                       0,                                                                                       0,                                                                                       0,                                                                                                                                                 0,                                                                                                                                                 0,                                                                                                                                               

In [88]:
def create_elements(num_initial_points):
    I = np.eye(60,60)
    blocks = [I]
    for i in range(59):
        I = np.roll(I,-1,0)
        I = sp.Matrix(I)
        blocks.append(I)
    elements = {f'g{i}':sp.BlockDiagMatrix(*[blocks[i]]*num_initial_points) for i in range(60)}
    return elements

In [89]:
A5_reg = create_elements(1)
sp.solve(A5_reg['g0'] - matrix)

SympifyError: SympifyError: array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])